[
{"code":"clown face","moji":"🤡","unicode":"1f921","category":"faces","tags":[],"link":null,"base":"clown_face","variants":["clown_face"],"score":338,"r18":false,"customizations":[],"combinations":[]}
,{"code":"bunny girl","moji":"👯","unicode":"1f46f","category":"people","tags":[],"link":null,"base":"bunny_girl","variants":["bunny_girl(wh)","bunny_girl(p)","bunny_girl(ye)","bunny_girl(br)","bunny_girl(bk)","bunny_girl","bunny_girl(simple)"],"score":332,"r18":false,"customizations":[],"combinations":[]},
{"code":"忍者","moji":null,"unicode":null,"category":"people","tags":[],"link":null,"base":"忍者","variants":["忍者"],"score":323,"r18":false,"customizations":[],"combinations":[]},
{"code":"emoji","moji":null,"unicode":null,"category":"symbols","tags":[],"link":null,"base":"emoji","variants":["emoji"],"score":322,"r18":false,"customizations":[],"combinations":[]},
{"code":"valentina","moji":null,"unicode":null,"category":"abstract","tags":["ולנטינה המלכה"],"link":null,"base":"valentina","variants":["valentina"],"score":321,"r18":false,"customizations":[],"combinations":[]},
{"code":"thinking face(smiley)","moji":null,"unicode":null,"category":"faces","tags":[],"link":null,"base":"thinking_face","variants":["thinking_face","thinking_face(smiley)","thinking_face(wh)","thinking_face(p)","thinking_face(ye)","thinking_face(br)","thinking_face(bk)"],"score":319,"r18":false,"customizations":[],"combinations":[]},
{"code":"face with thermometer(smiley)","moji":null,"unicode":null,"category":"faces","tags":[],"link":null,"base":"face_with_thermometer","variants":["face_with_thermometer(wh)","face_with_thermometer(p)","face_with_thermometer(ye)","face_with_thermometer(br)","face_with_thermometer(bk)","face_with_thermometer","face_with_thermometer(smiley)"],"score":317,"r18":false,"customizations":[],"combinations":[]},
{"code":"deadpool emblem","moji":null,"unicode":null,"category":"symbols","tags":["Marvel Comics","Deadpool","emblem"],"link":null,"base":"deadpool_emblem","variants":["deadpool_emblem"],"score":315,"r18":false,"customizations":[],"combinations":[]},
{"code":"(salmon)sushi","moji":null,"unicode":null,"category":"food","tags":[],"link":null,"base":"sushi","variants":["(salmon)sushi","sushi","(squid)sushi","(salmon_roe)sushi","(eel)sushi","(sea_urchin)sushi","(shrimp)sushi","(cucumber_roll)sushi","(egg)sushi","(conger_eel)sushi","(snapper)sushi","(tuna_roll)sushi","(salad_roll)sushi","(salmon_roll)sushi"],"score":314,"r18":false,"customizations":[],"combinations":[]}
,{"code":"taco","moji":"🌮","unicode":"1f32e","category":"food","tags":[],"link":null,"base":"taco","variants":["taco"],"score":314,"r18":false,"customizations":[],"combinations":[]},
{"code":"sufganiyot","moji":null,"unicode":null,"category":"food","tags":[],"link":null,"base":"sufganiyot","variants":["sufganiyot"],"score":314,"r18":false,"customizations":[],"combinations":[]},
{"code":"custard","moji":"🍮","unicode":"1f36e","category":"food","tags":[],"link":null,"base":"custard","variants":["custard"],"score":313,"r18":false,"customizations":[],"combinations":[]},
{"code":"middle finger(p)","moji":"🖕🏼","unicode":"1f595-1f3fc","category":"gestures","tags":[],"link":null,"base":"middle_finger","variants":["middle_finger(wh)","middle_finger(p)","middle_finger(ye)","middle_finger(br)","middle_finger(bk)","middle_finger"],"score":311,"r18":false,"customizations":[],"combinations":[]},
{"code":"stuck out tongue(smiley)","moji":null,"unicode":null,"category":"faces","tags":[],"link":null,"base":"stuck_out_tongue","variants":["stuck_out_tongue(smiley)","stuck_out_tongue(wh)","stuck_out_tongue","stuck_out_tongue(poop)","stuck_out_tongue(slime)","stuck_out_tongue(pudding)","stuck_out_tongue(ye)","stuck_out_tongue(br)","stuck_out_tongue(bk)","stuck_out_tongue(p)","stuck_out_tongue(dumpling)"],"score":307,"r18":false,"customizations":[],"combinations":[]},
{"code":"ブリトー","moji":"🌯","unicode":"1f32f","category":"food","tags":[],"link":null,"base":"ブリトー","variants":["ブリトー"],"score":307,"r18":false,"customizations":[],"combinations":[]}
,{"code":"turned ok hand sign(p)","moji":"🖏🏼","unicode":"1f58f-1f3fc","category":"gestures","tags":[],"link":null,"base":"turned_ok_hand_sign","variants":["turned_ok_hand_sign(wh)","turned_ok_hand_sign(p)","turned_ok_hand_sign(ye)","turned_ok_hand_sign(br)","turned_ok_hand_sign(bk)","turned_ok_hand_sign"],"score":305,"r18":false,"customizations":[],"combinations":[]},
{"code":"タクシー","moji":"🚕","unicode":"1f695","category":"transportation","tags":[],"link":null,"base":"タクシー","variants":["タクシー"],"score":304,"r18":false,"customizations":[],"combinations":[]},
{"code":"Present Miku","moji":null,"unicode":null,"category":"abstract","tags":["hatsune miku"],"link":null,"base":"Present_Miku","variants":["Present_Miku"],"score":304,"r18":false,"customizations":[],"combinations":[]},
{"code":"izzy","moji":null,"unicode":null,"category":"faces","tags":["Isabelle","Animal Crossing","meme","r34"],"link":null,"base":"izzy","variants":["izzy"],"score":303,"r18":false,"customizations":[],"combinations":[]},
{"code":"kawaii pikachu","moji":null,"unicode":null,"category":"faces","tags":["pika"],"link":null,"base":"kawaii_pikachu","variants":["kawaii_pikachu"],"score":303,"r18":false,"customizations":[],"combinations":[]},
{"code":"minecraft gold ingot","moji":null,"unicode":null,"category":"abstract","tags":["Minecraft"],"link":null,"base":"minecraft_gold_ingot","variants":["minecraft_gold_ingot"],"score":302,"r18":false,"customizations":[],"combinations":[]},
{"code":"superman","moji":null,"unicode":null,"category":"abstract","tags":["superman"],"link":null,"base":"superman","variants":["superman"],"score":301,"r18":false,"customizations":[],"combinations":[]},
{"code":"scuba diver","moji":null,"unicode":null,"category":"people","tags":[],"link":null,"base":"scuba_diver","variants":["scuba_diver"],"score":300,"r18":false,"customizations":[],"combinations":[]}],"meta":{"count":50,"total_count":8257,"page":1}}